### ISSUE TITLE
Some way of differentiating between analog inputs and digital inputs bound to a OneAxisPlayerAction

### ISSUE THREAD

**Issue by Alloc86** [pbhogan/InControlSupport#29]
Current situation: We have a OneAxisPlayerAction that we use for switching through your toolbar entries which defaults to being bound to the mouse wheel. It's queried by actionSet.Scroll.Value. In that setup everything works fine of course.

Issue is that if the user decides to bind normal buttons to the positive/negative actions instead though the Value property of the OneAxisPlayerAction will return a positive/negative value as long as the button is pressed instead of just OnPress/OnRelease.

Is there any way of getting that Axis stuff to work with button events in addition to analog inputs? Maybe some kind of option for AxisActions like "ButtonOnAction" that has "WasPressed", "WasReleased", "IsPressed" as values and then if the inputs are digital inputs it will only set Value to +1/-1 if the event matches and if it's bound to analog inputs it works as it does now?

**Comment by pbhogan** [comment]
I'm not sure I understand this. 

> the Value property of the OneAxisPlayerAction will return a positive/negative value as long as the button is pressed instead of just OnPress/OnRelease.

This is exactly what it is supposed to do. It does that with analogs too... if you hold down a trigger then it keeps its value until you let go. If you're looking for WasPressed behavior, use WasPressed. IsPressed will return the true as long as it is held and Value for digital controls will be 1 as long as it is held down.

There is really very little different internally whether a control is digital or analog. The only practical difference is digital only ever returns 0 or 1 and analogs can go the whole gradient between -1 and +1.

What you're probably running into is scroll wheels tend to only fire a value for a brief moment as the scroll wheel turns/clicks. There is no way to hold up or down on a scroll wheel other than to keep spinning it. It's kind of an unconventional control in that regard.

You could use WasPressed (possibly along with setting a higher StateThreshold) instead of using the control value itself. WasRepeated is also useful for UI movement. Alternatively, use LastInputType to determine that it is mouse input and behave differently between mouse and keyboard/controller input on that particular action.

**Comment by Alloc86** [comment]
Yeah, don't really see how this could be solved in a generic way.

Issue was that with a OneAxisAction you don't have WasPressed (well, you have one, but you wouldn't know the direction ;) ) so Value was our only choice here. Of course we could stick to the two independent actions and do something like Value=ScrollUp-ScrollDown and in this case we could also use WasPressed on each (considering them to be 0/1). But then again it would still kill the ability of a mouse wheel to not only increment by 1 but more than that, used for zooming the weapon scope.

Anyway, we have solved this now by providing two other actions for cycling through the toolbelt which are meant to be used with buttons, as the controller support had them anyway :)
